In [1]:
import pandas as pd

import dfconverter

In [2]:
raw_df1 = pd.read_csv("new_testdata/test-277.csv")
raw_df2 = pd.read_csv("new_testdata/test-311.csv")
raw_df3 = pd.read_csv("new_testdata/test-361.csv")
raw_df4 = pd.read_csv("new_testdata/test-374.csv")

In [3]:
df1 = dfconverter.converter(raw_df1)
df2 = dfconverter.converter(raw_df2)
df3 = dfconverter.converter(raw_df3)
df4 = dfconverter.converter(raw_df4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8470 entries, 0 to 8469
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   _time         8470 non-null   datetime64[ns, Asia/Tokyo]
 1   _measurement  8470 non-null   object
 2   co2           8470 non-null   float64
 3   humidity      8470 non-null   float64
 4   temperature   8470 non-null   float64
dtypes: datetime64[ns, Asia/Tokyo](1), float64(3), object(1)
memory usage: 331.0+ KB
None

/Users/engineer_1/co2/dfconverter.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = np.nan
/Users/engineer_1/co2/dfconverter.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["_time"][i] = df["_time"][i].replace(tzinfo=None)
/Users/engineer_1/co2/dfconverter.py:252: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = np.nan
/Users/engineer_1/co2/dfconverter.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:138: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:156: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:161: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:177: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:182: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:198: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:203: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:219: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:224: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:240: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:154: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   _time         8000 non-null   datetime64[ns, Asia/Tokyo]
 1   _measurement  8000 non-null   object
 2   co2           8000 non-null   float64
 3   humidity      8000 non-null   float64
 4   temperature   8000 non-null   float64
dtypes: datetime64[ns, Asia/Tokyo](1), float64(3), object(1)
memory usage: 312.6+ KB
None

/Users/engineer_1/co2/dfconverter.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = np.nan
/Users/engineer_1/co2/dfconverter.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["_time"][i] = df["_time"][i].replace(tzinfo=None)
/Users/engineer_1/co2/dfconverter.py:252: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = np.nan
/Users/engineer_1/co2/dfconverter.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:138: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:156: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:161: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:177: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:182: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:198: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:203: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:219: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:224: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:240: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:154: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.3
/Users/engineer_1/co2/dfconverter.py:175: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:196: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8121 entries, 0 to 8120
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   _time         8121 non-null   datetime64[ns, Asia/Tokyo]
 1   _measurement  8121 non-null   object
 2   co2           8121 non-null   float64
 3   humidity      8121 non-null   float64
 4   temperature   8121 non-null   float64
dtypes: datetime64[ns, Asia/Tokyo](1), float64(3), object(1)
memory usage: 317.4+ KB
None

/Users/engineer_1/co2/dfconverter.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = np.nan
/Users/engineer_1/co2/dfconverter.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["_time"][i] = df["_time"][i].replace(tzinfo=None)
/Users/engineer_1/co2/dfconverter.py:252: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = np.nan
/Users/engineer_1/co2/dfconverter.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:138: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:154: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.3
/Users/engineer_1/co2/dfconverter.py:161: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:175: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:182: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:196: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:203: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:219: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:224: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:240: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:156: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:177: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:198: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = np.nan
/Users/engineer_1/co2/dfconverter.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["_time"][i] = df["_time"][i].replace(tzinfo=None)
/Users/engineer_1/co2/dfconverter.py:252: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = np.nan
/Users/engineer_1/co2/dfconverter.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0
/Users/engineer_1/co2/dfconverter.py:138: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:154: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.3
/Users/engineer_1/co2/dfconverter.py:161: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:175: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:182: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:196: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:203: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:217: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:224: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = room[id_to_num[df["_measurement"][i]]][
/Users/engineer_1/co2/dfconverter.py:130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0.7
/Users/engineer_1/co2/dfconverter.py:219: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7423 entries, 0 to 7422
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   _time         7423 non-null   datetime64[ns, Asia/Tokyo]
 1   _measurement  7423 non-null   object
 2   co2           7423 non-null   float64
 3   humidity      7423 non-null   float64
 4   temperature   7423 non-null   float64
dtypes: datetime64[ns, Asia/Tokyo](1), float64(3), object(1)
memory usage: 290.1+ KB
None

/Users/engineer_1/co2/dfconverter.py:240: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["y"][i] = 0

In [8]:
display(df1)
display(df2)
display(df3)
display(df4)

        co2  humidity  temperature  seat_num  y
1682  502.0      17.1         25.5        80  0
1683  501.0      17.0         25.5        80  0
1684  502.0      17.1         25.5        80  0
1685  503.0      17.1         25.5        80  0
1686  505.0      17.1         25.5        80  0
...     ...       ...          ...       ... ..
8465  567.0      17.7         27.4        80  0
8466  567.0      17.7         27.4        80  0
8467  567.0      17.7         27.4        80  0
8468  567.0      17.6         27.4        80  0
8469  567.0      17.7         27.4        80  0

[3983 rows x 5 columns]

        co2  humidity  temperature  seat_num  y
1589  536.0      25.1         23.6       183  0
1590  536.0      25.1         23.6       183  0
1591  537.0      25.1         23.7       183  0
1592  537.0      25.1         23.7       183  0
1593  537.0      25.1         23.7       183  0
...     ...       ...          ...       ... ..
7995  706.0      24.4         25.8       183  0
7996  703.0      24.4         25.8       183  0
7997  702.0      24.5         25.8       183  0
7998  701.0      24.5         25.8       183  0
7999  700.0      24.5         25.8       183  0

[3762 rows x 5 columns]

        co2  humidity  temperature  seat_num  y
1614  676.0      23.7         24.3        56  1
1615  685.0      23.7         24.3        56  1
1616  694.0      23.7         24.3        56  1
1617  706.0      23.7         24.4        56  1
1618  711.0      23.7         24.4        56  1
...     ...       ...          ...       ... ..
8116  600.0      24.5         24.6        56  0
8117  598.0      24.5         24.6        56  0
8118  598.0      24.6         24.6        56  0
8119  599.0      24.6         24.6        56  0
8120  599.0      24.6         24.6        56  0

[3817 rows x 5 columns]

        co2  humidity  temperature  seat_num  y
1510  493.0      18.2         24.0        56  0
1511  493.0      18.3         24.1        56  0
1512  492.0      18.1         24.1        56  0
1513  493.0      18.0         24.1        56  0
1514  493.0      17.9         24.1        56  0
...     ...       ...          ...       ... ..
7418  558.0      21.9         25.1        56  0
7419  559.0      21.9         25.1        56  0
7420  559.0      21.9         25.1        56  0
7421  558.0      21.9         25.1        56  0
7422  557.0      21.9         25.1        56  0

[3332 rows x 5 columns]

In [7]:
import pickle
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    mean_absolute_error,
    mean_squared_log_error,
)
import numpy as np

model = pd.read_pickle("pycaretmodel.pkl")


# test_dfの特徴量
test_X = df1[["co2", "humidity", "temperature", "seat_num"]]
# 実際のyの値
actual_y = df1["y"]

# テストデータに対する予測
predicted_y = model.predict(test_X)

# 評価指標の計算
rmse = np.sqrt(mean_squared_error(actual_y, predicted_y))
r2 = r2_score(actual_y, predicted_y)
mae = mean_absolute_error(actual_y, predicted_y)
rmsle = np.sqrt(mean_squared_log_error(actual_y, predicted_y))


print("RMSE: ", rmse)
print("R2: ", r2)
print("MAE: ", mae)
print("RMSLE: ", rmsle)
print("------------------------")

RMSE:  0.30523096452360476
R2:  -4.615146402791657
MAE:  0.25824676012629216
RMSLE:  0.25334126747300534
------------------------